### ISSUE TITLE
Implimenting...android Newbie

### ISSUE THREAD

**Issue by mrrcomp** [FutureStateMobile/AppCore.Data#11]
Hi

I'm new to android/C# . i saw this Package. My question is how do I create the FutureState object to connect to SQL .

I added the using FutureState.AppCore.Data .. but can't see how to define the object :(

Would appreciate your kind help

Regards

Meir

**Comment by ChaseFlorell** [comment]
Hello @mrrcomp, very sorry for the delay. I missed this and have been on hiatus for a while.

What exactly are you trying to do? You don't need to create any "object" per-se, you just create your models and your schema.

Here's an example of creating a table.  
https://github.com/FutureStateMobile/AppCore.Data/wiki/Creating-a-Migration

And then you can query and update your table like so.
https://github.com/FutureStateMobile/AppCore.Data/wiki/DbProvider-Extensions 

If you have specific questions, please post back here.
